### ISSUE TITLE
Fix CI checks

### ISSUE THREAD

**Issue by jeffmaher** [Bloom-Works/handbook#134]
# Stories

As a developer and contributor, I want status checks to reliably tell me if something is wrong with the code.

# Notes

There is some inline styling that is causing the continuous integration checks to fail. If any additionaal info is needed, check-in with @coreycaitlin .

# Done When

- [ ] Code is refactored such that status checks pass again

**Comment by coreycaitlin** [comment]
Yep! I commented out the search in the top nav bar to hide it, since it wasn't functional. This caused the "home" link in the center of that top nav bar to be off-center, so I added inline styling to force it back to center.

Could fix by refactoring styles OR making search work so it doesn't have to be commented out.

**Comment by ghost** [comment]
@coreycaitlin or @dottiebobottie : Ready for review in #153 . See the preview link to see if everything still looks the same as production.
